- id: pymarkdown
  name: PyMarkdown
  description: "PyMarkdown - GitHub Flavored Markdown and CommonMark Compliant Linter"
  language: python
  language_version: python3
  entry: pymarkdown
  args: [scan]
  types: [markdown]
