# pytest.ini
[pytest]
testpaths=./test
cache_dir=./build/test/.pytest_cache
junit_family=xunit2
markers=
    gfm: gfm
    plugins: plugins
    rules: rules
    user_properties: user_properties
python_classes=NoThanks
addopts=--timeout=10 --cov-fail-under=50 --strict-markers -ra
