extensions:
  front-matter:
    enabled: true
plugins:
  ul-indent:
    enabled: false
  no-trailing-punctuation:
    enabled: false
  list-anchored-indent:
    enabled: true

        # "list-marker-space" : {
        #     "enabled": false
        # },
